### PR TITLE
fixScreenshot

### PR DESCRIPTION
**Pull request by YardWill**
The screenshot is about the previous version. So I replace it with a new screenshot in V2 API.

### CODE REVIEW

**Comment by acro5piano** [comment]
Thank you very much!

Can you correct the comment and query like this? It is more straightforward:

image

**Comment by YardWill** [comment]
Can i just download your picture to replace the old one? ￣▽￣

**Comment by acro5piano** [comment]
Sure, thanks!

----------------------------------------------------------------
五所和哉 Kay Gosho

+810-7808-4235
https://github.com/acro5piano
https://www.linkedin.com/in/kay-gosho-587a05121/
----------------------------------------------------------------

**Comment by acro5piano** [comment]
Thank you!

**Comment by YardWill** [comment]
Happy to do that!

**Pull request merged**
